apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - client-depl.yaml
 

images:
  - name: ghcr.io/beltawn3507/food_client
    newTag: bba5f7dbfe5f27fbfe0ad707d908b36438c74250
