apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - client-depl.yaml
 

images:
  - name: ghcr.io/beltawn3507/food_client
    newTag: 6f96ccf237fa58b4a2eb3313e515673384b42e10
