apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - client-depl.yaml
 

images:
  - name: ghcr.io/beltawn3507/food_client
    newTag: ec2e15d95e1cc1e428522425db724cd7ea93453b
