apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - payment_depl.yaml
  - payment-secret.yaml

images:
  - name: ghcr.io/beltawn3507/food_payment
    newTag: 27687aa50e96833c5af77e7e1543bd36f8f3056d
