apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-depl.yaml
  - auth-secrets.yaml

images:
  - name: ghcr.io/beltawn3507/food_auth
    newTag: bf6efb441413128c75977def6a7869346360dce6

