apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - realtime_depl.yaml

images:
  - name: ghcr.io/beltawn3507/food_realtime
    newTag: e4f84238e7140c2076830b78b24e6b6d545df4ba
