apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - realtime_depl.yaml

images:
  - name: ghcr.io/beltawn3507/food_realtime
    newTag: b4ced48ef76ba59587bb6f13de6fc4a2b7d24968
