apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - realtime_depl.yaml

images:
  - name: ghcr.io/beltawn3507/food_realtime
    newTag: 89a2634401dc1c6cf3a0809002e1f485c5bd6f0e
