apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-redis-depl
  namespace: food
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-redis
  template:
    metadata:
      labels:
        app: rest-redis
    spec:
      containers:
        - name: rest-redis
          image: redis
          args:
            - "--maxmemory"
            - "128mb"
            - "--maxmemory-policy"
            - "allkeys-lru"

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: rest-redis-srv
  namespace: food
spec:
  selector:
    app: rest-redis
  ports:
    - name: db
      protocol: TCP
      port: 6379
      targetPort: 6379
